apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: ecommerce
  labels:
    app: mongodb
    service: database
spec:
  storageClassName: ecommerce-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
