apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: ecommerce
  labels:
    type: local
    service: mongodb
spec:
  storageClassName: ecommerce-ssd
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/mongodb-data
