services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "5001:5001"
    volumes:
      - user-data:/app/data
    networks:
      - microservices-network

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "5002:5002"
    volumes:
      - order-data:/app/data
    environment:
      - USER_SERVICE_URL=http://user-service:5001
    depends_on:
      - user-service
    networks:
      - microservices-network

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "5003:5003"
    networks:
      - microservices-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_URL=http://user-service:5001
      - ORDER_SERVICE_URL=http://order-service:5002
      - PAYMENT_SERVICE_URL=http://payment-service:5003
    depends_on:
      - user-service
      - order-service
      - payment-service
    networks:
      - microservices-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - microservices-network

volumes:
  user-data:
  order-data:

networks:
  microservices-network:
    driver: bridge
