services:
  user-service:
    image: prakashbhati086/user-service:${BUILD_NUMBER:-latest}
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  order-service:
    image: prakashbhati086/order-service:${BUILD_NUMBER:-latest}
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
      - USER_SERVICE_URL=http://user-service:5001
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  payment-service:
    image: prakashbhati086/payment-service:${BUILD_NUMBER:-latest}
    ports:
      - "5003:5003"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - JAVA_OPTS=-Xmx512m -Xms256m
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  api-gateway:
    image: prakashbhati086/api-gateway:${BUILD_NUMBER:-latest}
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - USER_SERVICE_URL=http://user-service:5001
      - ORDER_SERVICE_URL=http://order-service:5002
      - PAYMENT_SERVICE_URL=http://payment-service:5003

  frontend:
    image: prakashbhati086/frontend:${BUILD_NUMBER:-latest}
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
